language: go
go:
  - 1.9.2

services:
  - docker

sudo: required

before_install:
  - docker version

script:
  - sudo make
  - sudo make acceptance_tests

after_install:
  - docker plugin ls
  # TODO: add docker plugin push ci, if merged to master
